default[:tow][:username] = "tow"
default[:tow][:repository_url] = "git@github.com:unkot/tow.git"
default[:tow][:branch] = "master"
default[:tow][:cassandra][:host] = "127.0.0.1"
default[:tow][:rabbitmq][:host] = "127.0.0.1"
default[:tow][:rabbitmq][:password] = "guest"
